apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: evqi9ugf6-python 
  janus-idp.io/tekton: evqi9ugf6-python
  backstage.io/kubernetes-id: evqi9ugf6-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: evqi9ugf6-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml